<?php if (!defined('ABSPATH')) exit;
$readonly = $message && $message->statut === 'envoye';
$m = $message ?: (object) array('id'=>0,'titre'=>'','corps'=>'','categorie'=>'information','cible_type'=>'all','cible_valeur'=>null,'canaux'=>'{"portail":true,"email":false,"push":false}','piece_jointe_id'=>null,'epingle'=>0,'accuse_requis'=>0,'date_envoi_prevue'=>null);
$target = json_decode((string) $m->cible_valeur, true) ?: array(); $channels = json_decode((string) $m->canaux, true) ?: array('email'=>false);
?>
<div class="wrap psc-messages-admin"><h1><?php echo $m->id ? esc_html__('Modifier le message', 'periscolaire-registration') : esc_html__('Nouveau message', 'periscolaire-registration'); ?></h1>
<?php if ($readonly): ?><div class="notice notice-info"><p><?php esc_html_e('Ce message a été envoyé : seul son épinglage peut encore être modifié.', 'periscolaire-registration'); ?></p></div><?php endif; ?>
<?php if (!empty($_GET['psc_msg'])): ?><div class="notice notice-info is-dismissible"><p><?php echo esc_html(sanitize_text_field(wp_unslash($_GET['psc_msg']))); ?></p></div><?php endif; ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" id="psc-message-form" data-readonly="<?php echo $readonly ? '1' : '0'; ?>" data-nonce-save="<?php echo esc_attr(wp_create_nonce('psc_save_message')); ?>" data-nonce-send="<?php echo esc_attr(wp_create_nonce('psc_send_message')); ?>" data-nonce-test="<?php echo esc_attr(wp_create_nonce('psc_test_message')); ?>">
<input type="hidden" name="action" id="psc-message-action" value="psc_save_message"><input type="hidden" name="submit_action" id="psc-message-submit-action" value="draft"><input type="hidden" name="id" value="<?php echo (int) $m->id; ?>">
<input type="hidden" name="_wpnonce" value="<?php echo esc_attr(wp_create_nonce('psc_save_message')); ?>">
<input type="hidden" name="send_token" value="<?php echo esc_attr(wp_generate_uuid4()); ?>">
<div class="psc-message-edit-grid"><div class="psc-message-panel">
<h2><?php esc_html_e('Contenu', 'periscolaire-registration'); ?></h2>
<fieldset <?php disabled($readonly); ?>><legend><?php esc_html_e('Catégorie', 'periscolaire-registration'); ?></legend><div class="psc-category-picker"><?php foreach ($categories as $slug=>$cat): ?><label class="psc-cat" style="--cat-bg:<?php echo esc_attr($cat['bg']); ?>;--cat-fg:<?php echo esc_attr($cat['fg']); ?>"><input type="radio" name="categorie" value="<?php echo esc_attr($slug); ?>" <?php checked($m->categorie,$slug); ?>><?php echo esc_html($cat['label']); ?></label><?php endforeach; ?></div></fieldset>
<label for="psc-message-title"><strong><?php esc_html_e('Titre', 'periscolaire-registration'); ?></strong></label><input id="psc-message-title" class="widefat" maxlength="160" name="titre" value="<?php echo esc_attr($m->titre); ?>" <?php disabled($readonly); ?>><p class="description"><span id="psc-title-count">0 / 80</span> — <?php esc_html_e("sert d'objet d'e-mail et de titre de notification", 'periscolaire-registration'); ?></p>
<label><strong><?php esc_html_e('Message', 'periscolaire-registration'); ?></strong></label><?php if($readonly): ?><div class="psc-message-rendered"><?php echo wp_kses($m->corps,Psc_Messages::allowed_html()); ?></div><?php else: wp_editor($m->corps, 'psc_message_body', array('textarea_name'=>'corps','teeny'=>true,'media_buttons'=>false,'textarea_rows'=>10)); endif; ?>
<div class="psc-attachment"><strong><?php esc_html_e('Pièce jointe', 'periscolaire-registration'); ?></strong><input type="hidden" id="psc-attachment-id" name="piece_jointe_id" value="<?php echo (int) $m->piece_jointe_id; ?>"><button type="button" class="button" id="psc-attachment-pick" <?php disabled($readonly); ?>><?php esc_html_e('Choisir un fichier', 'periscolaire-registration'); ?></button> <span id="psc-attachment-label"><?php echo $m->piece_jointe_id ? esc_html(get_the_title($m->piece_jointe_id)) : ''; ?></span> <button type="button" class="button-link-delete" id="psc-attachment-remove" <?php disabled($readonly); ?>><?php esc_html_e('Retirer', 'periscolaire-registration'); ?></button><p class="description">PDF, JPG ou PNG · 5 Mo maximum.</p></div>
<p><label><input type="checkbox" name="epingle" value="1" <?php checked($m->epingle); ?>> <?php esc_html_e('Épingler en tête de la liste des familles', 'periscolaire-registration'); ?></label><br><label><input type="checkbox" name="accuse_requis" value="1" <?php checked($m->accuse_requis); disabled($readonly); ?>> <?php esc_html_e('Demander un accusé de lecture explicite', 'periscolaire-registration'); ?></label></p>
<div class="psc-message-actions"><?php if (!$readonly): ?><button class="button button-primary button-large" data-message-action="send"><?php printf(esc_html__('Envoyer à %d familles', 'periscolaire-registration'), $target_count['familles']); ?></button><input type="datetime-local" name="date_envoi_prevue" value="<?php echo esc_attr($m->date_envoi_prevue ? date('Y-m-d\TH:i', strtotime($m->date_envoi_prevue)) : ''); ?>"><button class="button" data-message-action="schedule"><?php esc_html_e('Programmer…', 'periscolaire-registration'); ?></button><button class="button-link" data-message-action="draft"><?php esc_html_e('Enregistrer en brouillon', 'periscolaire-registration'); ?></button><button class="button-link" data-message-action="test"><?php esc_html_e("M'envoyer un test", 'periscolaire-registration'); ?></button><?php else: ?><button class="button button-primary" data-message-action="pin"><?php esc_html_e('Enregistrer l’épinglage', 'periscolaire-registration'); ?></button><?php endif; ?></div>
</div><aside>
<div class="psc-message-panel"><h2><?php esc_html_e('Destinataires', 'periscolaire-registration'); ?></h2><fieldset <?php disabled($readonly); ?>>
<?php foreach (array('all'=>'Toutes les familles','ecole'=>'Une école','service'=>'Un service','familles'=>'Familles précises') as $slug=>$label): ?><label class="psc-target"><input type="radio" name="cible_type" value="<?php echo esc_attr($slug); ?>" <?php checked($m->cible_type,$slug); ?>> <?php echo esc_html($label); ?></label><?php endforeach; ?>
<select name="cible_ecole"><option value="maternelle" <?php selected($target['ecole'] ?? '','maternelle'); ?>>Maternelle</option><option value="elementaire" <?php selected($target['ecole'] ?? 'elementaire','elementaire'); ?>>Élémentaire</option></select>
<select name="cible_service"><option value="cantine">Cantine</option><option value="accueil_matin">Accueil du matin</option><option value="accueil_soir">Accueil du soir</option></select>
<select name="family_ids[]" multiple size="7" class="widefat"><?php foreach ($families as $family): ?><option value="<?php echo (int)$family->id; ?>" <?php selected(in_array((int)$family->id,array_map('intval',$target['family_ids'] ?? array()),true)); ?>><?php echo esc_html(trim($family->prenom.' '.$family->nom).' — '.$family->email); ?></option><?php endforeach; ?></select></fieldset>
<p id="psc-target-count"><strong><?php echo (int)$target_count['familles']; ?> familles</strong> · <?php echo (int)$target_count['enfants']; ?> enfants concernés</p></div>
<div class="psc-message-panel"><h2><?php esc_html_e('Canaux de diffusion', 'periscolaire-registration'); ?></h2><p><label><input type="checkbox" checked disabled> Espace famille</label><br><label><input type="checkbox" name="canal_email" value="1" <?php checked(!empty($channels['email'])); disabled($readonly); ?>> E-mail</label><br><label><input type="checkbox" name="canal_push" value="1" <?php checked(!empty($channels['push'])); disabled($readonly); ?>> Notification navigateur</label></p></div>
<div class="psc-message-preview"><small><?php esc_html_e('Aperçu notification', 'periscolaire-registration'); ?></small><span id="psc-preview-cat" class="psc-cat"></span><strong id="psc-preview-title"></strong><p id="psc-preview-body"></p></div>
</aside></div></form>
<dialog id="psc-send-confirm" class="psc-send-dialog"><h2><?php esc_html_e('Confirmer l’envoi','periscolaire-registration'); ?></h2><p><?php esc_html_e('Le ciblage sera figé et ce message ne pourra plus être modifié.','periscolaire-registration'); ?></p><div id="psc-send-summary"></div><p><button type="button" class="button" id="psc-send-cancel"><?php esc_html_e('Annuler','periscolaire-registration'); ?></button> <button type="button" class="button button-primary" id="psc-send-confirm-button"><?php esc_html_e('Confirmer l’envoi','periscolaire-registration'); ?></button></p></dialog>
<?php if ($m->id): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" onsubmit="return confirm('Supprimer ce message ?');"><input type="hidden" name="action" value="psc_delete_message"><input type="hidden" name="id" value="<?php echo (int)$m->id; ?>"><?php wp_nonce_field('psc_delete_message'); ?><button class="button-link-delete"><?php esc_html_e('Supprimer le message', 'periscolaire-registration'); ?></button></form><?php endif; ?></div>
